# Generated by Django 2.1 on 2021-06-29 23:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, max_length=1000)),
                ('gamma', models.FloatField(default=1.0)),
                ('classified', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None)),
                ('modelSelection', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=None)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
