# Generated by Django 2.1 on 2021-06-06 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, max_length=1000)),
                ('gamma', models.FloatField(default=1.0)),
                ('rank5_classified', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='unknown', max_length=10, null=True), size=None)),
                ('rank5_probability', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=0.0, null=True), size=None)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
