# Generated by Django 2.1 on 2021-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='classified',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
