# Generated by Django 2.1 on 2021-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='gamma',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
