# Generated by Django 2.1 on 2021-05-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_auto_20210530_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='picture',
            new_name='sequence',
        ),
    ]
